# Example git checkout from Ansible Playbooks
- name: Hello World!
  hosts: all
  tasks:
  - name: Hello World!
    git:
      repo: https://github.com/haxxorsid/stock-management-system.git
      dest: /srv/checkout
