- name: Hello World Sample
  hosts: all
  vars: 
    - name: "githubuser" 
      value: "nilayrane" 
      private: no 
    - name: "githubpassword" 
      value: "dhampya2497" 
      private: yes 
  tasks:
    - name: Git clone
      expect:
        command: git clone https://github.com/nilayrane/test.git /srv/checkout2
        responses:
          Username: "{{ githubuser }}" # Username is a regex
          Password: "{{ githubpassword }}" # Password is a regex
