- name: Hello World Sample
  hosts: all
  vars: 
    githubuser: nilayrane 
    githubpassword: dhampya2497 
  tasks:
    - name: Git clone
      expect:
        command: git clone https://github.com/nilayrane/test.git /srv/checkout3
        responses:
          Username: "{{ user }}" # Username is a regex
          Password: "{{ pass }}" # Password is a regex
