- name: Hello World Sample
  hosts: all
  vars_prompt: 
    - name: "githubuser" 
      value: "nilayrane" 
      private: no 
    - name: "githubpassword" 
      value: "dhampya2497" 
      private: yes 
  tasks:
    - name: Ensure remote URL does not contain credentials
      git:
        name: remote.origin.url
        value: https://github.com/nilayrane/test.git
        scope: local
        repo: /srv/checkout2
