- name: Hello World Sample
  hosts: all
  vars: 
    githubuser: nilayrane 
    githubpassword: dhampya2497 
  tasks:
    - name: Install pip
      expect:
        command: sudo yum install python-pip
        
    - name: Install pexpect
      pip:
        name: pexpect
        
    - name: Git clone
      expect:
        command: git clone https://github.com/nilayrane/test.git /srv/checkout2
        responses:
          Username: "{{ githubuser }}" # Username is a regex
          Password: "{{ githubpassword }}" # Password is a regex
