- name: Hello World Sample
  hosts: all
  tasks:
    - name: Git clone
      expect:
        command: rm -rf /srv/checkout3/linuxusers
        responses:
    - name: Git clone
      expect:
        command: git clone https://github.com/nilayrane/test.git /srv/checkout3
        responses:
          Username: "{{ user }}" # Username is a regex
          Password: "{{ pass }}" # Password is a regex
